### PR TITLE
Migrate to Mojmap

### PR DESCRIPTION
**Pull request by ChampionAsh5357**
This PR updates all entries to use the mojmap field/method names.

### CODE REVIEW

**Review by AterAnimAvis — DISMISSED** [review]

**Comment by ravenbuilder934** [comment]
Should there be a note somewhere about mojmap vs mcp? (Or it's already there and I missed it)

**Comment by ChampionAsh5357** [comment]
There isn't one, probably should be although most people would ignore it. I don't know where it should be put though.

**Review by ravenbuilder934 — DISMISSED** [review]
still missing the difference between mojmaps and MCP (parameters, missing names, etc) 😛 but close enough, and that might be out of scope anyway

**Comment by 50ap5ud5** [comment]
I think it would be good to add a summary comment about what the official mappings provide, perhaps in the first paragraph of the "Migration to Mojang Mappings" section in index.md. 

"...for the forseeable future. 

These official mappings provide names for all Class, Methods and Fields, though Parameters and Javadocs are not provided."

https://github.com/forgecommunitywiki/Documentation/pull/37/files#diff-b1e471a018a9434fa2f890e2a0836c7395875eef90d6fb011907be613195a9e7R49

Also, since this is for 1.16, perhaps mention the the mods.toml file and the mandatory license field in the "Customizing Your Mod Information" section under index.md?

**Comment by ChampionAsh5357** [comment]
Sure enough. As for the mandatory license field, it was added in a PR a while back by raven. Actually, I think it was the first pr to this branch.

**Review by ravenbuilder934 — APPROVED** [review]

**Review by 50ap5ud5 — APPROVED** [review]

**Review by AterAnimAvis — CHANGES_REQUESTED** [review]
~~WorldSavedData has a couple of mcp names (`markDirty` -> `setDirty`, `getMapStorage` -> `getDataStorage`) and needs a rewrite for 1.16 (seperate PR?). Otherwise looks good.~~

**Review by AterAnimAvis — APPROVED** [review]

**Pull request merged**
