### PR TITLE
Add local copies of icons

### PR DESCRIPTION
**Pull request by sciwhiz12**
This PR adds local copies of icons, which were previously present on the forums site. This removes references to the forums site (which according to the linked issue, causing a not insignificant amount of traffic when visitors try to retrieve the non-existent files), and fixes the favicons of the docs site.

Addresses MinecraftForge#366.

### CODE REVIEW

**Comment by ChampionAsh5357** [comment]
It seems as though this doesn't address the favicon for android chrome or windows metro. It might be good to generate these as well since it is in the scope.

**Comment by sciwhiz12** [comment]
This now addresses all favicons, by copying from the master MinecraftForge/Web repository (specifically, [the images/favicons directory](https://github.com/MinecraftForge/Web/tree/5e085382cfce0b915ac35abc0eac35d668dc6c4d/images/favicons)).

**Review by ChampionAsh5357 — COMMENTED** [review]
`mstile-144x144.png` goes unused. Should be implemented within the tiles for the application or removed.

**Comment by sciwhiz12** [comment]
Removed the 144x144 tile icon, as according to the [Microsoft docs on the Browser configuration schema](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/dn320426(v=vs.85)), specifically the section on "Specifying tile images and assets", there is no equivalent entry for a 144x144 icon.

**Review by ChampionAsh5357 — APPROVED** [review]

**Pull request merged**
